### ISSUE TITLE
Tb-profiler issue

### ISSUE THREAD

**Issue by MarcNiebel** [Pathogen-Genomics-Cymru/lodestone#58]
I have only recently started using Lodestone but am having an error that is cropping up. I have added an example.
[tbprofiler.errlog.txt](https://github.com/user-attachments/files/15551509/tbprofiler.errlog.txt). It seems to relate to `Input is not detected as bcf or vcf format` which might relate to https://github.com/jodyphelan/TBProfiler/issues/367. However I was also wondering if it is a version issue (tb-profiler 6.2.0 versus 6.2.1) because when I run the aformentioned samples using a conda environment with tb-profiler no issuses arise.

**Comment by WhalleyT** [comment]
Hi Marc, apologies I've been on annual leave. I also suspect it is probably a version issue. we've been having a lot of issues with clashing errors in TBProfiler vs TBDB.  From looking at the log I'm guessing you've run it from one of our prebuilt containers? 

Thanks for flagging this! Hopefully we'll get it sorted sharpish

**Comment by MarcNiebel** [comment]
Hi Tom,
Thanks for responding. Yes I am using your singularity containers. Hopefully you can resolve it. 
Marc

**Comment by WhalleyT** [comment]
Hi again. So the issue was that the Github Actions workflow had failed because the newest version of tb-profiler wasn't on the conda channel yet. I've pushed the workflow to run again and bumped the version of that container to 0.9.8.1; so if you pull the latest version it should work. I've just run a few samples through and they work but let me know if you're still having problems.

p.s. there may be a few changes to this container because it doesn't seem to like some versions of Singularity

**Comment by MarcNiebel** [comment]
Hi Tom, unfortunately this is still not working. Any ideas?
[error_log_lodestone_180624.txt](https://github.com/user-attachments/files/15886861/error_log_lodestone_180624.txt)

**Comment by jodyphelan** [comment]
Hi @MarcNiebel 

I just noticed this github issue via another one that I was helping on. Was this solved? Happy to taka a look

**Comment by MarcNiebel** [comment]
Hi @jodyphelan,

@WhalleyT resolved this. Thanks.
